---
- name: Play book to connect with network devices
  hosts: all
  connection: ansible.netcommon.network_cli
  tasks:
    - name: getting cisco facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: debugging the output
      ansible.builtin.debug:
        msg: '{{ ansible_facts }}'

