---
- name: Play book to connect with network devices
  hosts: all
  connection: ansible.netcommon.network_cli
  tasks:
    - name: debugging the output
      ansible.builtin.debug:
        msg: '{{ ansible_play_hosts }}'

