---
- name: Play book to check ios_commands module
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  tasks:
    - name: checking ignore errors task option
      cisco.ios.ios_command:
        commands:
          - show ip int br
      register: output
      no_log: true
      

    - name: debugging the output
      ansible.builtin.debug:
        msg: 
         - "{{ ansible_user }}"


