---
- name: Play book to connect with network devices
  hosts: localhost
  vars:
    my_name: 'Sandeep'
  tasks:
  - name: env lookup
    ansible.builtin.debug:
      msg: 
        - "{{ lookup( 'env','HOME') }}"