---
- name: Play book to connect with network devices
  hosts: localhost
  connection: ansible.netcommon.network_cli
  tasks:
  - name: file lookup
    ansible.builtin.debug:
      msg: 
        - "{{ lookup('file','my_txt.txt')}}"
        - "{{ lookup('file','my_txt.db', errors='ignore')}}"
        - "{{ lookup('file','my_txt.db', errors='warn')}}"
    
