---
- name: Play book to connect with network devices
  hosts: localhost
  connection: ansible.netcommon.network_cli
  gather_facts: true
  tasks:
  - name: Printing the output
    ansible.builtin.debug:
      msg: "{{ ansible_facts.keys() }}"
    when: 
      - "{{ 'python' in  ansible_facts.keys() }}"
      #- "{{ }}"
    
