---
- name: Play book to connect with network devices
  hosts: all
  connection: ansible.netcommon.network_cli
  vars:
  gather_facts: true
  tasks:
  - name: Run show version on remote devices
    ansible.netcommon.cli_command:
      command: 'show version'
    register: output

  - name: Printing the output
    ansible.builtin.debug:
      msg:
        - "{{ output }}"
